networks:
  todo_network:

volumes:
  todo_pg_data:

services:
  todo_backend_service:
    image: todo
    container_name: todo_container
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - API_PORT=8080
      - CORS_ALLOWED=http://localhost:3000
      - MAINTENANCE_MODE=0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=todos
      - DB_USER=todo_user
      - DB_PASSWORD=todoUser$123
      - DB_DIALECT=postgres
    networks:
      - todo_network
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/app/src

  postgres:
    image: postgres
    container_name: todo-pg-container
    environment:
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: todoUser$123
      POSTGRES_USER: todo_user
    networks:
      - todo_network
    ports:
      - '5432:5432'
    volumes:
      - todo_pg_data:/var/lib/postgresql/data